//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NexxtSao.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Presupuesto.
        /// </summary>
        public static string Button_Estimate_Edit {
            get {
                return ResourceManager.GetString("Button_Estimate_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presupuesto.
        /// </summary>
        public static string Button_Estimate_New {
            get {
                return ResourceManager.GetString("Button_Estimate_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        public static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string ButtonDetail {
            get {
                return ResourceManager.GetString("ButtonDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia.
        /// </summary>
        public static string ButtonMedical {
            get {
                return ResourceManager.GetString("ButtonMedical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string ButtonNew {
            get {
                return ResourceManager.GetString("ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        public static string ButtonPrint {
            get {
                return ResourceManager.GetString("ButtonPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte.
        /// </summary>
        public static string ButtonReport {
            get {
                return ResourceManager.GetString("ButtonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organiza las Citas de todos los Odontologos y permite que cada Odontologo pueda entrar a Revisar o Ingresar nuevas Citas. .
        /// </summary>
        public static string CardCitas_Texto {
            get {
                return ResourceManager.GetString("CardCitas_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibe los Pagos de tratamientos y realiza el pago Odontologos por Tratamiento realizado, todo segun sus procentajes..
        /// </summary>
        public static string CardCobros_Texto {
            get {
                return ResourceManager.GetString("CardCobros_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registra los Odontologos y asigna Porcentaje por Categoria, podran varias sus porcentajes segun el tratamiento..
        /// </summary>
        public static string CardOdontologos_Texto {
            get {
                return ResourceManager.GetString("CardOdontologos_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria Tratamiento.
        /// </summary>
        public static string CategoryTreatments_Model_Category {
            get {
                return ResourceManager.GetString("CategoryTreatments_Model_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string CategoryTreatments_Model_Company {
            get {
                return ResourceManager.GetString("CategoryTreatments_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria Tratamientos.
        /// </summary>
        public static string CategoryTreatments_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("CategoryTreatments_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string City_Model_City {
            get {
                return ResourceManager.GetString("City_Model_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string City_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("City_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacientes.
        /// </summary>
        public static string Client_IndeView_titulo1 {
            get {
                return ResourceManager.GetString("Client_IndeView_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion.
        /// </summary>
        public static string Client_Model_Address {
            get {
                return ResourceManager.GetString("Client_Model_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movil.
        /// </summary>
        public static string Client_Model_Cell {
            get {
                return ResourceManager.GetString("Client_Model_Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string Client_Model_City {
            get {
                return ResourceManager.GetString("Client_Model_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacientes.
        /// </summary>
        public static string Client_Model_Cliente {
            get {
                return ResourceManager.GetString("Client_Model_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compania.
        /// </summary>
        public static string Client_Model_Compania {
            get {
                return ResourceManager.GetString("Client_Model_Compania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Client_Model_Date {
            get {
                return ResourceManager.GetString("Client_Model_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string Client_Model_Email {
            get {
                return ResourceManager.GetString("Client_Model_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Client_Model_FirstName {
            get {
                return ResourceManager.GetString("Client_Model_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia.
        /// </summary>
        public static string Client_Model_Hsitoria {
            get {
                return ResourceManager.GetString("Client_Model_Hsitoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string Client_Model_LastName {
            get {
                return ResourceManager.GetString("Client_Model_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacimiento.
        /// </summary>
        public static string Client_Model_Nacimiento {
            get {
                return ResourceManager.GetString("Client_Model_Nacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero Documento.
        /// </summary>
        public static string Client_Model_NumerIdentification {
            get {
                return ResourceManager.GetString("Client_Model_NumerIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Client_Model_Phone {
            get {
                return ResourceManager.GetString("Client_Model_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Documento.
        /// </summary>
        public static string Client_Model_TipoDocu {
            get {
                return ResourceManager.GetString("Client_Model_TipoDocu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        public static string Client_Model_Zone {
            get {
                return ResourceManager.GetString("Client_Model_Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia Clinica.
        /// </summary>
        public static string ClienteHistory_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("ClienteHistory_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string ClienteHistory_Model_Detalle {
            get {
                return ResourceManager.GetString("ClienteHistory_Model_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embarazo.
        /// </summary>
        public static string ClienteHistory_Model_Embarazo {
            get {
                return ResourceManager.GetString("ClienteHistory_Model_Embarazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string ClientHisotry_Model_Company {
            get {
                return ResourceManager.GetString("ClientHisotry_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epilepsia.
        /// </summary>
        public static string ClientHisotry_Model_Epilepsia {
            get {
                return ResourceManager.GetString("ClientHisotry_Model_Epilepsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transtorno Gastrico.
        /// </summary>
        public static string ClientHisotry_Model_TransGastrico {
            get {
                return ResourceManager.GetString("ClientHisotry_Model_TransGastrico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transtorno Respiratorio.
        /// </summary>
        public static string ClientHisotry_Model_TransRepiratorio {
            get {
                return ResourceManager.GetString("ClientHisotry_Model_TransRepiratorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alergias.
        /// </summary>
        public static string ClientHistory_Model_Alergias {
            get {
                return ResourceManager.GetString("ClientHistory_Model_Alergias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardiopatias.
        /// </summary>
        public static string ClientHistory_Model_Cardiopatias {
            get {
                return ResourceManager.GetString("ClientHistory_Model_Cardiopatias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cirugias (Incluye Orales).
        /// </summary>
        public static string ClientHistory_Model_Cirugias {
            get {
                return ResourceManager.GetString("ClientHistory_Model_Cirugias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paciente.
        /// </summary>
        public static string ClientHistory_Model_Cliente {
            get {
                return ResourceManager.GetString("ClientHistory_Model_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string ClientHistory_Model_Date {
            get {
                return ResourceManager.GetString("ClientHistory_Model_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabetes.
        /// </summary>
        public static string ClientHistory_Model_Diabetes {
            get {
                return ResourceManager.GetString("ClientHistory_Model_Diabetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discracias Sanguineas.
        /// </summary>
        public static string ClientHistory_Model_Discracias {
            get {
                return ResourceManager.GetString("ClientHistory_Model_Discracias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiebre Reumatica.
        /// </summary>
        public static string ClientHistory_Model_FiebreReumatica {
            get {
                return ResourceManager.GetString("ClientHistory_Model_FiebreReumatica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuma o Consume LIcor.
        /// </summary>
        public static string ClientHistory_Model_Fumalico {
            get {
                return ResourceManager.GetString("ClientHistory_Model_Fumalico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hepatitis.
        /// </summary>
        public static string ClientHistory_Model_Hepatitis {
            get {
                return ResourceManager.GetString("ClientHistory_Model_Hepatitis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inmunosupresion.
        /// </summary>
        public static string ClientHistory_Model_Inmunosupresion {
            get {
                return ResourceManager.GetString("ClientHistory_Model_Inmunosupresion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irradiaciones.
        /// </summary>
        public static string ClientHistory_Model_Irradiaciones {
            get {
                return ResourceManager.GetString("ClientHistory_Model_Irradiaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toma Medicamentos.
        /// </summary>
        public static string ClientHistory_Model_Medicamento {
            get {
                return ResourceManager.GetString("ClientHistory_Model_Medicamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tratamiento Medico.
        /// </summary>
        public static string ClientHistory_Model_MedicoActual {
            get {
                return ResourceManager.GetString("ClientHistory_Model_MedicoActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteracion Presion Arterial.
        /// </summary>
        public static string ClientHistory_Model_PresionArterial {
            get {
                return ResourceManager.GetString("ClientHistory_Model_PresionArterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enfermedades Renales.
        /// </summary>
        public static string ClientHistory_Model_Ranales {
            get {
                return ResourceManager.GetString("ClientHistory_Model_Ranales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transtorno Emocional.
        /// </summary>
        public static string ClientHistory_Model_TransEmoacional {
            get {
                return ResourceManager.GetString("ClientHistory_Model_TransEmoacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enfermedad Oral.
        /// </summary>
        public static string ClientHistoy_Model_EnfermedadOral {
            get {
                return ResourceManager.GetString("ClientHistoy_Model_EnfermedadOral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otras Alteraciones.
        /// </summary>
        public static string ClientHistoy_Model_OtrasAlteraciones {
            get {
                return ResourceManager.GetString("ClientHistoy_Model_OtrasAlteraciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color_Model_ColorDate {
            get {
                return ResourceManager.GetString("Color_Model_ColorDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color_Model_IndexTitulo1 {
            get {
                return ResourceManager.GetString("Color_Model_IndexTitulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Seleccione Item...].
        /// </summary>
        public static string ComboSelect {
            get {
                return ResourceManager.GetString("ComboSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Company_Model_Active {
            get {
                return ResourceManager.GetString("Company_Model_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion.
        /// </summary>
        public static string Company_Model_Address {
            get {
                return ResourceManager.GetString("Company_Model_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulado.
        /// </summary>
        public static string Company_Model_Anulado {
            get {
                return ResourceManager.GetString("Company_Model_Anulado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string Company_Model_Compania {
            get {
                return ResourceManager.GetString("Company_Model_Compania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais.
        /// </summary>
        public static string Company_Model_Country {
            get {
                return ResourceManager.GetString("Company_Model_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        public static string Company_Model_Desde {
            get {
                return ResourceManager.GetString("Company_Model_Desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta.
        /// </summary>
        public static string Company_Model_Hasta {
            get {
                return ResourceManager.GetString("Company_Model_Hasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Company_Model_Logo {
            get {
                return ResourceManager.GetString("Company_Model_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Company_Model_Phone {
            get {
                return ResourceManager.GetString("Company_Model_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string Company_Model_Precio {
            get {
                return ResourceManager.GetString("Company_Model_Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nit/CI.
        /// </summary>
        public static string Company_Model_Rif {
            get {
                return ResourceManager.GetString("Company_Model_Rif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string Company_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Company_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais.
        /// </summary>
        public static string Country_Model_Pais {
            get {
                return ResourceManager.GetString("Country_Model_Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais.
        /// </summary>
        public static string Country_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Country_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Dentist_Model_Active {
            get {
                return ResourceManager.GetString("Dentist_Model_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion.
        /// </summary>
        public static string Dentist_Model_Address {
            get {
                return ResourceManager.GetString("Dentist_Model_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string Dentist_Model_City {
            get {
                return ResourceManager.GetString("Dentist_Model_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario.
        /// </summary>
        public static string Dentist_Model_Comentario {
            get {
                return ResourceManager.GetString("Dentist_Model_Comentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string Dentist_Model_Company {
            get {
                return ResourceManager.GetString("Dentist_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Dentist_Model_Date {
            get {
                return ResourceManager.GetString("Dentist_Model_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odontologo.
        /// </summary>
        public static string Dentist_Model_Dentist {
            get {
                return ResourceManager.GetString("Dentist_Model_Dentist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero Documento.
        /// </summary>
        public static string Dentist_Model_DocumentNumber {
            get {
                return ResourceManager.GetString("Dentist_Model_DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Dentist_Model_FirstName {
            get {
                return ResourceManager.GetString("Dentist_Model_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string Dentist_Model_LastName {
            get {
                return ResourceManager.GetString("Dentist_Model_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        public static string Dentist_Model_Movil {
            get {
                return ResourceManager.GetString("Dentist_Model_Movil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Dentist_Model_Phone {
            get {
                return ResourceManager.GetString("Dentist_Model_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string Dentist_Model_Photo {
            get {
                return ResourceManager.GetString("Dentist_Model_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentaje.
        /// </summary>
        public static string Dentist_Model_Porcentaje {
            get {
                return ResourceManager.GetString("Dentist_Model_Porcentaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialidad.
        /// </summary>
        public static string Dentist_Model_Specialty {
            get {
                return ResourceManager.GetString("Dentist_Model_Specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Documento.
        /// </summary>
        public static string Dentist_Model_TypeDocument {
            get {
                return ResourceManager.GetString("Dentist_Model_TypeDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string Dentist_Model_UserName {
            get {
                return ResourceManager.GetString("Dentist_Model_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        public static string Dentist_Model_Zone {
            get {
                return ResourceManager.GetString("Dentist_Model_Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odontologos.
        /// </summary>
        public static string Dentist_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Dentist_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentajes.
        /// </summary>
        public static string DentistPercentage_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("DentistPercentage_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string DentistPercentage_Model_Category {
            get {
                return ResourceManager.GetString("DentistPercentage_Model_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string DentistPercentage_Model_Company {
            get {
                return ResourceManager.GetString("DentistPercentage_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odontologo.
        /// </summary>
        public static string DentistPercentage_Model_Dentist {
            get {
                return ResourceManager.GetString("DentistPercentage_Model_Dentist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentaje.
        /// </summary>
        public static string DentistPercentage_Model_Rate {
            get {
                return ResourceManager.GetString("DentistPercentage_Model_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string DentistSpecialty_Model_Company {
            get {
                return ResourceManager.GetString("DentistSpecialty_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialidad.
        /// </summary>
        public static string DentistSpecialty_Model_Especialidad {
            get {
                return ResourceManager.GetString("DentistSpecialty_Model_Especialidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialidades.
        /// </summary>
        public static string DentistSpecialty_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("DentistSpecialty_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos Generales.
        /// </summary>
        public static string DirectGeneral_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("DirectGeneral_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string DirectGeneral_Model_Cantidad {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paciente.
        /// </summary>
        public static string DirectGeneral_Model_Cliente {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string DirectGeneral_Model_Company {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobante Pago.
        /// </summary>
        public static string DirectGeneral_Model_ComprobantePago {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_ComprobantePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string DirectGeneral_Model_Date {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encabezado.
        /// </summary>
        public static string DirectGeneral_Model_Encabezado {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Encabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturado.
        /// </summary>
        public static string DirectGeneral_Model_Facturado {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Facturado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Facturado.
        /// </summary>
        public static string DirectGeneral_Model_FechaFacturado {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_FechaFacturado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota Cobro.
        /// </summary>
        public static string DirectGeneral_Model_NotaCobro {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_NotaCobro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string DirectGeneral_Model_Precio {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago Odontologo.
        /// </summary>
        public static string DirectGeneral_Model_ProcentajeProfesional {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_ProcentajeProfesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odontologo.
        /// </summary>
        public static string DirectGeneral_Model_Profesional {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Profesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tratamiento.
        /// </summary>
        public static string DirectGeneral_Model_Servicio {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasa Odontologo.
        /// </summary>
        public static string DirectGeneral_Model_TasaProfesional {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_TasaProfesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string DirectGeneral_Model_Tax {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string DirectGeneral_Model_Total {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobro Directo.
        /// </summary>
        public static string DirectPayment_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("DirectPayment_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string DirectPayment_Model_Cantidad {
            get {
                return ResourceManager.GetString("DirectPayment_Model_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string DirectPayment_Model_Categoria {
            get {
                return ResourceManager.GetString("DirectPayment_Model_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paciente.
        /// </summary>
        public static string DirectPayment_Model_Cliente {
            get {
                return ResourceManager.GetString("DirectPayment_Model_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string DirectPayment_Model_Company {
            get {
                return ResourceManager.GetString("DirectPayment_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string DirectPayment_Model_Date {
            get {
                return ResourceManager.GetString("DirectPayment_Model_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel Precio.
        /// </summary>
        public static string DirectPayment_Model_LevelPrice {
            get {
                return ResourceManager.GetString("DirectPayment_Model_LevelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota Cobro.
        /// </summary>
        public static string DirectPayment_Model_NotaCobro {
            get {
                return ResourceManager.GetString("DirectPayment_Model_NotaCobro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string DirectPayment_Model_Precio {
            get {
                return ResourceManager.GetString("DirectPayment_Model_Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odontologo.
        /// </summary>
        public static string DirectPayment_Model_Profesional {
            get {
                return ResourceManager.GetString("DirectPayment_Model_Profesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string DirectPayment_Model_Rate {
            get {
                return ResourceManager.GetString("DirectPayment_Model_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tratamiento.
        /// </summary>
        public static string DirectPayment_Model_Servicio {
            get {
                return ResourceManager.GetString("DirectPayment_Model_Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasa Odontologo.
        /// </summary>
        public static string DirectPayment_Model_TasaProfesional {
            get {
                return ResourceManager.GetString("DirectPayment_Model_TasaProfesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string DirectPayment_Model_Total {
            get {
                return ResourceManager.GetString("DirectPayment_Model_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EstimadeDetailAdd_ {
            get {
                return ResourceManager.GetString("EstimadeDetailAdd_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Presupuesto.
        /// </summary>
        public static string EstimadeDetailAdd_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("EstimadeDetailAdd_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string EstimadeDetailAdd_Model_Cantidad {
            get {
                return ResourceManager.GetString("EstimadeDetailAdd_Model_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string EstimadeDetailAdd_Model_Categoria {
            get {
                return ResourceManager.GetString("EstimadeDetailAdd_Model_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string EstimadeDetailAdd_Model_Company {
            get {
                return ResourceManager.GetString("EstimadeDetailAdd_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presupuesto.
        /// </summary>
        public static string EstimadeDetailAdd_Model_Estimate {
            get {
                return ResourceManager.GetString("EstimadeDetailAdd_Model_Estimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel Precio.
        /// </summary>
        public static string EstimadeDetailAdd_Model_LevelPrice {
            get {
                return ResourceManager.GetString("EstimadeDetailAdd_Model_LevelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasa.
        /// </summary>
        public static string EstimadeDetailAdd_Model_Tasa {
            get {
                return ResourceManager.GetString("EstimadeDetailAdd_Model_Tasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string EstimadeDetailAdd_Model_Total {
            get {
                return ResourceManager.GetString("EstimadeDetailAdd_Model_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tratamiento.
        /// </summary>
        public static string EstimadeDetailAdd_Model_Tratamiento {
            get {
                return ResourceManager.GetString("EstimadeDetailAdd_Model_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unitario.
        /// </summary>
        public static string EstimadeDetailAdd_Model_Unitario {
            get {
                return ResourceManager.GetString("EstimadeDetailAdd_Model_Unitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string EstimatDetail_Model_Total {
            get {
                return ResourceManager.GetString("EstimatDetail_Model_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presupuesto.
        /// </summary>
        public static string Estimate_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("Estimate_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paciente.
        /// </summary>
        public static string Estimate_Model_Client {
            get {
                return ResourceManager.GetString("Estimate_Model_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string Estimate_Model_Company {
            get {
                return ResourceManager.GetString("Estimate_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Estimate_Model_Date {
            get {
                return ResourceManager.GetString("Estimate_Model_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encabezado.
        /// </summary>
        public static string Estimate_Model_Encabezado {
            get {
                return ResourceManager.GetString("Estimate_Model_Encabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presupuesto.
        /// </summary>
        public static string Estimate_Model_Estimado {
            get {
                return ResourceManager.GetString("Estimate_Model_Estimado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string Estimate_Model_Impuesto {
            get {
                return ResourceManager.GetString("Estimate_Model_Impuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total.
        /// </summary>
        public static string Estimate_Model_SubTotal {
            get {
                return ResourceManager.GetString("Estimate_Model_SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Estimate_Model_Total {
            get {
                return ResourceManager.GetString("Estimate_Model_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Presupuesto.
        /// </summary>
        public static string EstimateDetail_IndeView_Titulo1 {
            get {
                return ResourceManager.GetString("EstimateDetail_IndeView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presupuesto.
        /// </summary>
        public static string EstimateDetail_IndeView_Titulo2 {
            get {
                return ResourceManager.GetString("EstimateDetail_IndeView_Titulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abono.
        /// </summary>
        public static string EstimateDetail_Model_Abono {
            get {
                return ResourceManager.GetString("EstimateDetail_Model_Abono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string EstimateDetail_Model_Cantidad {
            get {
                return ResourceManager.GetString("EstimateDetail_Model_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string EstimateDetail_Model_Category {
            get {
                return ResourceManager.GetString("EstimateDetail_Model_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diente.
        /// </summary>
        public static string EstimateDetail_Model_Diente {
            get {
                return ResourceManager.GetString("EstimateDetail_Model_Diente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimado.
        /// </summary>
        public static string EstimateDetail_Model_EstemateId {
            get {
                return ResourceManager.GetString("EstimateDetail_Model_EstemateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo.
        /// </summary>
        public static string EstimateDetail_Model_Saldo {
            get {
                return ResourceManager.GetString("EstimateDetail_Model_Saldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasa.
        /// </summary>
        public static string EstimateDetail_Model_Tasa {
            get {
                return ResourceManager.GetString("EstimateDetail_Model_Tasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tratamiento.
        /// </summary>
        public static string EstimateDetail_Model_Tratamiento {
            get {
                return ResourceManager.GetString("EstimateDetail_Model_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tratamiento.
        /// </summary>
        public static string EstimateDetail_Model_Treatment {
            get {
                return ResourceManager.GetString("EstimateDetail_Model_Treatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unitario.
        /// </summary>
        public static string EstimateDetail_Model_Unitario {
            get {
                return ResourceManager.GetString("EstimateDetail_Model_Unitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asistio.
        /// </summary>
        public static string Event_Model_Asistencia {
            get {
                return ResourceManager.GetString("Event_Model_Asistencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paciente.
        /// </summary>
        public static string Event_Model_Cliente {
            get {
                return ResourceManager.GetString("Event_Model_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Event_Model_Color {
            get {
                return ResourceManager.GetString("Event_Model_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string Event_Model_Compania {
            get {
                return ResourceManager.GetString("Event_Model_Compania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Event_Model_DateEnd {
            get {
                return ResourceManager.GetString("Event_Model_DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Event_Model_DateStart {
            get {
                return ResourceManager.GetString("Event_Model_DateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string Event_Model_Description {
            get {
                return ResourceManager.GetString("Event_Model_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia Completo.
        /// </summary>
        public static string Event_Model_FullDay {
            get {
                return ResourceManager.GetString("Event_Model_FullDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        public static string Event_Model_Hora {
            get {
                return ResourceManager.GetString("Event_Model_Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo.
        /// </summary>
        public static string Event_Model_Motivo {
            get {
                return ResourceManager.GetString("Event_Model_Motivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odontologo.
        /// </summary>
        public static string Event_Model_Professional {
            get {
                return ResourceManager.GetString("Event_Model_Professional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string Event_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Event_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Evolucion.
        /// </summary>
        public static string Evolucion_Detail_Evolucion {
            get {
                return ResourceManager.GetString("Evolucion_Detail_Evolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolucion.
        /// </summary>
        public static string Evolution_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Evolution_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encabezado.
        /// </summary>
        public static string HeadText_IndexViewTitulo1 {
            get {
                return ResourceManager.GetString("HeadText_IndexViewTitulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string HeadText_Model_Compania {
            get {
                return ResourceManager.GetString("HeadText_Model_Compania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto Encabezado.
        /// </summary>
        public static string HeadText_Model_Texto {
            get {
                return ResourceManager.GetString("HeadText_Model_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda de Cita.
        /// </summary>
        public static string Home_Card1_Agenda {
            get {
                return ResourceManager.GetString("Home_Card1_Agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odontologos.
        /// </summary>
        public static string Home_Card2_Odontolo {
            get {
                return ResourceManager.GetString("Home_Card2_Odontolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobros y Pagos.
        /// </summary>
        public static string Home_Card3_Pagos {
            get {
                return ResourceManager.GetString("Home_Card3_Pagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        public static string Hora_Model_Horas {
            get {
                return ResourceManager.GetString("Hora_Model_Horas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        public static string Hora_Model_IndexTitulo1 {
            get {
                return ResourceManager.GetString("Hora_Model_IndexTitulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden.
        /// </summary>
        public static string Hora_Model_Orden {
            get {
                return ResourceManager.GetString("Hora_Model_Orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Documento.
        /// </summary>
        public static string Identification_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("Identification_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Identification_Model_Company {
            get {
                return ResourceManager.GetString("Identification_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Codumento.
        /// </summary>
        public static string Identification_Model_TipoDocumento {
            get {
                return ResourceManager.GetString("Identification_Model_TipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotos.
        /// </summary>
        public static string ImgFotoEstimate_Titulo1 {
            get {
                return ResourceManager.GetString("ImgFotoEstimate_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periapicales.
        /// </summary>
        public static string ImgPeriapicalesEstimate_Titulo1 {
            get {
                return ResourceManager.GetString("ImgPeriapicalesEstimate_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel Precio.
        /// </summary>
        public static string LevelPrice_Modal_NivelPrecio {
            get {
                return ResourceManager.GetString("LevelPrice_Modal_NivelPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel Precio.
        /// </summary>
        public static string LevelPrice_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("LevelPrice_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema de Acceso.
        /// </summary>
        public static string MenuAcceso {
            get {
                return ResourceManager.GetString("MenuAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Usuario.
        /// </summary>
        public static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Sistema/Texto Encabezado, podra cambiar por la direccion, telefono y correo.
        /// </summary>
        public static string Msg_Compny_CreateHeadtext {
            get {
                return ResourceManager.GetString("Msg_Compny_CreateHeadtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe un Registro con el mismo Valor.
        /// </summary>
        public static string Msg_DoubleData {
            get {
                return ResourceManager.GetString("Msg_DoubleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Campo {0} debe ser menor de {1} characters.
        /// </summary>
        public static string Msg_MaxLength {
            get {
                return ResourceManager.GetString("Msg_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Item Tiene Abonos y no puede ser Borrado.
        /// </summary>
        public static string Msg_NoDoleteItem {
            get {
                return ResourceManager.GetString("Msg_NoDoleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Existen Registros para Continuar.
        /// </summary>
        public static string Msg_NoRegisterToContinue {
            get {
                return ResourceManager.GetString("Msg_NoRegisterToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Nuevo Precio no puede ser Menos al Abono Existente.
        /// </summary>
        public static string Msg_NoTotalMenorAbono {
            get {
                return ResourceManager.GetString("Msg_NoTotalMenorAbono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Seleccionar un Item.
        /// </summary>
        public static string Msg_Range {
            get {
                return ResourceManager.GetString("Msg_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Registo no puede ser Eliminado, porque tiene relacion con otros Datos.
        /// </summary>
        public static string Msg_Relationship {
            get {
                return ResourceManager.GetString("Msg_Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Campo {0} es Requerido.
        /// </summary>
        public static string Msg_Required {
            get {
                return ResourceManager.GetString("Msg_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desea Eliminar este Registro?.
        /// </summary>
        public static string MsgDelete {
            get {
                return ResourceManager.GetString("MsgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software para odontologos SAO.
        /// </summary>
        public static string NombreSoftware {
            get {
                return ResourceManager.GetString("NombreSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Consulta.
        /// </summary>
        public static string Orthodoncia_DetalleConsulta {
            get {
                return ResourceManager.GetString("Orthodoncia_DetalleConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotos.
        /// </summary>
        public static string Orthodoncia_Fotos {
            get {
                return ResourceManager.GetString("Orthodoncia_Fotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ortodoncia.
        /// </summary>
        public static string Orthodoncia_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("Orthodoncia_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paciente Detalle.
        /// </summary>
        public static string Orthodoncia_Paciente {
            get {
                return ResourceManager.GetString("Orthodoncia_Paciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panoramicas.
        /// </summary>
        public static string Orthodoncia_Panoramica {
            get {
                return ResourceManager.GetString("Orthodoncia_Panoramica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago Odontologo.
        /// </summary>
        public static string PayDentist_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("PayDentist_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string PayDentist_Model_Company {
            get {
                return ResourceManager.GetString("PayDentist_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string PayDentist_Model_Date {
            get {
                return ResourceManager.GetString("PayDentist_Model_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string PayDentist_Model_Detalle {
            get {
                return ResourceManager.GetString("PayDentist_Model_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota Pago.
        /// </summary>
        public static string PayDentist_Model_NotaPago {
            get {
                return ResourceManager.GetString("PayDentist_Model_NotaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Pago.
        /// </summary>
        public static string PayDentist_Model_PagoProfessional {
            get {
                return ResourceManager.GetString("PayDentist_Model_PagoProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odontologo.
        /// </summary>
        public static string PayDentist_Model_Professional {
            get {
                return ResourceManager.GetString("PayDentist_Model_Professional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos Odontologos.
        /// </summary>
        public static string PayDentistDetail_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("PayDentistDetail_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string PayDentistDetail_Model_Company {
            get {
                return ResourceManager.GetString("PayDentistDetail_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string PayDentistDetail_Model_Date {
            get {
                return ResourceManager.GetString("PayDentistDetail_Model_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota Cobro.
        /// </summary>
        public static string PayDentistDetail_Model_NotaCobro {
            get {
                return ResourceManager.GetString("PayDentistDetail_Model_NotaCobro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago Odontologo.
        /// </summary>
        public static string PayDentistDetail_Model_PagoProf {
            get {
                return ResourceManager.GetString("PayDentistDetail_Model_PagoProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago Odontolgo.
        /// </summary>
        public static string PayDentistDetail_Model_PayDentist {
            get {
                return ResourceManager.GetString("PayDentistDetail_Model_PayDentist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos Generales.
        /// </summary>
        public static string PayDentistDetail_Model_PaymentGeneral {
            get {
                return ResourceManager.GetString("PayDentistDetail_Model_PaymentGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota Cobro.
        /// </summary>
        public static string Register_Model_BillingNote {
            get {
                return ResourceManager.GetString("Register_Model_BillingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presupuesto.
        /// </summary>
        public static string Register_Model_Estimate {
            get {
                return ResourceManager.GetString("Register_Model_Estimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia.
        /// </summary>
        public static string Register_Model_History {
            get {
                return ResourceManager.GetString("Register_Model_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota Pago.
        /// </summary>
        public static string Register_Model_NotaPago {
            get {
                return ResourceManager.GetString("Register_Model_NotaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ortodoncia.
        /// </summary>
        public static string Register_Model_Ortodoncia {
            get {
                return ResourceManager.GetString("Register_Model_Ortodoncia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutivo.
        /// </summary>
        public static string Register_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Register_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string Tax_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("Tax_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compania.
        /// </summary>
        public static string Tax_Model_Company {
            get {
                return ResourceManager.GetString("Tax_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string Tax_Model_Impuesto {
            get {
                return ResourceManager.GetString("Tax_Model_Impuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasa.
        /// </summary>
        public static string Tax_Model_Tasa {
            get {
                return ResourceManager.GetString("Tax_Model_Tasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tratamientos.
        /// </summary>
        public static string Treatment_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("Treatment_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string Treatment_Model_Categoria {
            get {
                return ResourceManager.GetString("Treatment_Model_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string Treatment_Model_Compania {
            get {
                return ResourceManager.GetString("Treatment_Model_Compania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string Treatment_Model_Detalle {
            get {
                return ResourceManager.GetString("Treatment_Model_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string Treatment_Model_Impuesto {
            get {
                return ResourceManager.GetString("Treatment_Model_Impuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio 1.
        /// </summary>
        public static string Treatment_Model_Precio1 {
            get {
                return ResourceManager.GetString("Treatment_Model_Precio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio 2.
        /// </summary>
        public static string Treatment_Model_Precio2 {
            get {
                return ResourceManager.GetString("Treatment_Model_Precio2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio 3.
        /// </summary>
        public static string Treatment_Model_Precio3 {
            get {
                return ResourceManager.GetString("Treatment_Model_Precio3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tratamiento.
        /// </summary>
        public static string Treatment_Model_Tratamiento {
            get {
                return ResourceManager.GetString("Treatment_Model_Tratamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion.
        /// </summary>
        public static string User_Model_Address {
            get {
                return ResourceManager.GetString("User_Model_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string User_Model_Company {
            get {
                return ResourceManager.GetString("User_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string User_Model_Email {
            get {
                return ResourceManager.GetString("User_Model_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string User_Model_FisrtName {
            get {
                return ResourceManager.GetString("User_Model_FisrtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string User_Model_FullName {
            get {
                return ResourceManager.GetString("User_Model_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string User_Model_LastName {
            get {
                return ResourceManager.GetString("User_Model_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string User_Model_Phone {
            get {
                return ResourceManager.GetString("User_Model_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string User_Model_Photo {
            get {
                return ResourceManager.GetString("User_Model_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puesto.
        /// </summary>
        public static string User_Model_Puesto {
            get {
                return ResourceManager.GetString("User_Model_Puesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string User_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("User_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string ViewCreate {
            get {
                return ResourceManager.GetString("ViewCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string ViewDelete {
            get {
                return ResourceManager.GetString("ViewDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string ViewDetail {
            get {
                return ResourceManager.GetString("ViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string ViewEdit {
            get {
                return ResourceManager.GetString("ViewEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        public static string Zone_Model_Zone {
            get {
                return ResourceManager.GetString("Zone_Model_Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        public static string Zone_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Zone_ViewIndex_Titulo1", resourceCulture);
            }
        }
    }
}
